---
collections:
  - id: guidance_pages
    label: Guidance pages
    label_single: Guidance page
    description: Guidance pages on www.planning.data.gov.uk
    field_map:
      id: id
      label: title
    fields:
      - { id: "id", label: "ID", type: "string", editable: false, required: true }
      - { id: "title", label: "Title", type: "string", editable: true, required: true }
      - { id: "body", label: "Body", type: "govspeak", editable: true }
  - id: specifications
    label: Specifications
    label_single: Specification
    description: Specifications for planning datasets
    field_map:
      id: specification
      label: name
    fields:
      - { id: "specification", label: "Specification ID (no spaces)", type: "string", required: true }
      - { id: "name", label: "Specification name", type: "string", editable: false, required: true }
      - { id: "plural", label: "Specification name (plural)", type: "string", editable: false, required: true }
      - { id: "specification-status", label: "Specification status", type: "string", default_value: "candidate-standard", editable: false, required: true }
      - { id: "start-date", label: "Start date", type: "date", editable: false }
      - { id: "end-date", label: "End date", type: "date", editable: false }
      - { id: "entry-date", label: "Entry date", type: "date", default_value: "now()", editable: false, required: true }
      - { id: "documentation-url", label: "Documentation URL", type: "string", editable: false }
      - { id: "github-discussion", label: "GitHub discussion", type: "string", editable: false }
      - { id: "version", label: "Version", type: "string", editable: false }
      - id: "datasets"
        label: "Datasets"
        label_single: "Dataset"
        type: "repeatable"
        field_map:
          id: dataset
          label: name
        fields:
          - { id: "dataset", label: "Dataset ID (no spaces)", type: "string", required: true }
          - { id: "name", label: "Dataset name", type: "string", editable: false, required: true }
          - id: "fields"
            label: "Fields"
            label_single: "Field"
            type: "repeatable"
            field_map:
              id: field
              label: field
            fields:
              - { id: "field", label: "Field", type: "string", required: true }
              - { id: "dataset-field", label: "Dataset Field", type: "string", required: false }
              - { id: "dataset", label: "Dataset", type: "string", required: false }
              - { id: "description", label: "Description", type: "text", editable: true }
              - { id: "guidance", label: "Guidance", type: "govspeak", editable: true }
  - id: data_design
    label: Data Design Collections
    label_single: Data Design Collection
    description: Collections stored for data design team
    field_map:
      id: id
      label: name
    fields:
      - { id: "id", label: "ID", type: "string", editable: false, required: true }
      - { id: "name", label: "Name", type: "string", editable: false, required: true }
      - id: events
        label: Data design events
        label_single: Data design event
        description: Events for Planning data design
        type: "repeatable"
        field_map:
          id: id
          label: name
        fields:
          - { id: "id", label: "ID", type: "string", default_value: "generate_uuid()", required: true }
          - { id: "name", label: "Name of event", type: "string", editable: true, required: true }
          - { id: "description", label: "Description", type: "text", editable: true, required: false }
          - { id: "audience", label: "Audience", type: "text", editable: true, required: false }
          - { id: "link", label: "Link", type: "text", editable: true, required: false }
          - { id: "start_time", label: "Start time", type: "datetime", default_value: "now()", editable: true, required: false }
          - { id: "end_time", label: "End time", type: "datetime", default_value: "now()", editable: true, required: false }
          - { id: "location", label: "Location", type: "string", editable: true, required: false }
          - { id: "joining_link", label: "Joining link", type: "string", editable: true, required: false }
          - { id: "owner", label: "Owner", type: "string", editable: true, required: false }
          - id: "type"
            label: "Type of event"
            type: "select"
            editable: true
            required: true
            default_value: "general"
            options:
              - { value: "general", label: "General event" }
              - { value: "community_drop_id", label: "Community Drop in" }
              - { value: "advisory_group", label: "Advisory Group" }
              - { value: "working_group", label: "Working Group" }
