# Schema for Digital Land specifications
version: 1.0

# Define the exact order of fields for each specification type
specifications:
  article-4-direction:
    order:
      - specification
      - name
      - plural
      - specification-status
      - start-date
      - end-date
      - entry-date
      - github-discussion
      - version
      - datasets
    fields:
      specification:
        type: string
        required: true
      name:
        type: string
        required: true
      plural:
        type: string
        required: true
      specification-status:
        type: string
        required: true
        default_value: "candidate-standard"
      start-date:
        type: date
      end-date:
        type: date
      entry-date:
        type: date
        required: true
        default_value: "now()"
      datasets:
        type: array
        items:
          type: object
          properties:
            dataset:
              type: string
              required: true
            name:
              type: string
              required: true
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    required: true
                  description:
                    type: text
                  guidance:
                    type: text

  brownfield-land:
    order:
      - specification
      - name
      - plural
      - specification-status
      - start-date
      - end-date
      - entry-date
      - github-discussion
      - version
      - datasets
    fields:
      specification:
        type: string
        required: true
      name:
        type: string
        required: true
      plural:
        type: string
        required: true
      specification-status:
        type: string
        required: true
        default_value: "candidate-standard"
      start-date:
        type: date
      end-date:
        type: date
      entry-date:
        type: date
        required: true
        default_value: "now()"
      datasets:
        type: array
        items:
          type: object
          properties:
            dataset:
              type: string
              required: true
            name:
              type: string
              required: true
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    required: true
                  description:
                    type: text
                  guidance:
                    type: text

  conservation-area:
    order:
      - specification
      - name
      - plural
      - specification-status
      - start-date
      - end-date
      - entry-date
      - github-discussion
      - version
      - datasets
    fields:
      specification:
        type: string
        required: true
      name:
        type: string
        required: true
      plural:
        type: string
        required: true
      specification-status:
        type: string
        required: true
        default_value: "candidate-standard"
      start-date:
        type: date
      end-date:
        type: date
      entry-date:
        type: date
        required: true
        default_value: "now()"
      datasets:
        type: array
        items:
          type: object
          properties:
            dataset:
              type: string
              required: true
            name:
              type: string
              required: true
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    required: true
                  description:
                    type: text
                  guidance:
                    type: text

  listed-building:
    order:
      - specification
      - name
      - plural
      - specification-status
      - start-date
      - end-date
      - entry-date
      - github-discussion
      - version
      - datasets
    fields:
      specification:
        type: string
        required: true
      name:
        type: string
        required: true
      plural:
        type: string
        required: true
      specification-status:
        type: string
        required: true
        default_value: "candidate-standard"
      start-date:
        type: date
      end-date:
        type: date
      entry-date:
        type: date
        required: true
        default_value: "now()"
      datasets:
        type: array
        items:
          type: object
          properties:
            dataset:
              type: string
              required: true
            name:
              type: string
              required: true
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    required: true
                  description:
                    type: text
                  guidance:
                    type: text

  tree-preservation-order:
    order:
      - specification
      - name
      - plural
      - specification-status
      - start-date
      - end-date
      - entry-date
      - github-discussion
      - version
      - datasets
    fields:
      specification:
        type: string
        required: true
      name:
        type: string
        required: true
      plural:
        type: string
        required: true
      specification-status:
        type: string
        required: true
        default_value: "candidate-standard"
      start-date:
        type: date
      end-date:
        type: date
      entry-date:
        type: date
        required: true
        default_value: "now()"
      datasets:
        type: array
        items:
          type: object
          properties:
            dataset:
              type: string
              required: true
            name:
              type: string
              required: true
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    required: true
                  description:
                    type: text
                  guidance:
                    type: text