name: Specifications Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/collections/specifications/**"
      - ".github/workflows/specifications.yml"

jobs:
  create-specification-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create specification pull request
        env:
          GITHUB_TOKEN: ${{ secrets.SPECIFICATION_PR_FINE_GRAIN_TOKEN }}
        run: |
          echo "Creating specification pull request"
          python src/specifications/update_specifications.py
